server:
  servlet:
    context-path: /circle-consumer-dev
  port: 8081

spring:
  application:
    name: circle-achieve-consumer
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: ALWAYS
    time-zone: GMT+8

circle:
  # 日志配置
  log:
    application-name: circle-achieve
    module-name: circle-achieve-consumer
    level: debug
    file:
      path: /Users/lewy/WorkSets/logSet/java/circle-achieve
  # swagger 配置
  swagger:
    enabled: true
    base-package: cn.xzxy.lewy.circleachieve
    contact:
      email: lewy95@aliyun.com
      name: Lewy Robert
      url: https://mail.aliyun.com/alimail/auth/login
    description: 'circle achieve swagger'
    title: achieve-consumer
    version: 1.0.0
