server:
  servlet:
    context-path: /circle-provider-pre
  port: 8082

spring:
  application:
    name: circle-achieve-provider
  profiles:
    active: pre
  #数据库配置
  datasource:
    #1.JDBC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sakila?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    druid:
      #2.连接池配置
      #初始化连接池的连接数量 大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      #配置获取连接等待超时的时间
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 是否缓存preparedStatement，也就是PSCache  官方建议MySQL下建议关闭   个人建议如果想用SQL防火墙 建议打开
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filter:
        stat:
          merge-sql: true
          slow-sql-millis: 5000
      #3.基础监控配置
      web-stat-filter:
        enabled: true
        url-pattern: /*
        #设置不统计哪些URL
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        session-stat-enable: true
        session-stat-max-count: 10
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        #设置监控页面的登录名和密码
        login-username: admin
        login-password: 123456
        allow: 127.0.0.1
        #deny: 122.1.1.1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: ALWAYS
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: cn.xzxy.lewy.circleachieve.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true  #开启驼峰

pagehelper:
  helper-dialect: mysql

circle:
  # 日志配置
  log:
    application-name: circle-achieve
    module-name: circle-achieve-provider
    level: debug
    file:
      path: /Users/lewy/WorkSets/logSet/java/circle-achieve
  # swagger 配置
  swagger:
    enabled: true
    base-package: cn.xzxy.lewy.circleachieve
    contact:
      email: lewy95@aliyun.com
      name: Lewy Robert
      url: https://mail.aliyun.com/alimail/auth/login
    description: 'circle achieve swagger'
    title: achieve-provider
    version: 1.0.0

